driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: rewrite-2.0
    run_list:
      - recipe[iis_urlrewrite::default]
  - name: rewrite-2.1
    attributes:
      iis_urlrewrite:
        version: "2.1"
    run_list:
      - recipe[iis_urlrewrite::default]
